name: Push Code to Another Repo

on:
  push:
    branches:
      - main # Trigger this on the 'main' branch push

jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code from the current repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Git for pushing code
      - name: Set up Git
        run: |
          git config --global user.name "soumya-work"
          git config --global user.email "soumyaranjansahuwork@gmail.com"

      # Step 3: Set the target repository as remote
      - name: Set target repository as remote
        run: |
          git remote set-url origin https://${{ secrets.PAT }}@github.com/soumya-work/devcode.git

      # Step 4: Push to Target Repository
      - name: Push to Target Repository
        run: |
          git push -u origin master --force
