name: Push Code from Dev to Prod Repo

on:
  push:
    branches: [ main ]  # Trigger the workflow on push to 'main' branch
  pull_request:
    branches: [ main ]  # Also trigger on pull requests to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex  # Optional container if required for the build

    steps:
      # Step 1: Checkout the code from the current repository
      - name: Checkout Dev Repository
        uses: actions/checkout@v2

      # Step 2: Install mustache (optional)
      - name: Install mustache
        run: |
          apk add ruby && gem install mustache

      # Step 3: Run build script
      - name: Run build.sh script
        run: |
          sh ./build.sh

      # Step 4: Push to Prodweb repository
      - name: Push code to Prodweb
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@target-branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}  # Use GitHub secret for the token
        with:
          source-directory: .  # Root directory to push
          destination-github-username: 'soumya-work'  # Your GitHub username
          destination-repository-name: 'prodweb'  # Name of the production repository
          user-email: 'soumyaranjansahuwork@gmail.com'  # Your email for commits
          commit-message: "Pushing changes from $GITHUB_REF"
          target-branch: beta  # Push to 'beta' branch in the prod repo

      # Step 5: Test exported variable
      - name: Echo the cloned directory path
        run: echo "Cloned directory: $DESTINATION_CLONED_DIRECTORY"
