name: Push Code from Dev to Prod

on:
  push:
    branches:
      - main  # Trigger on the 'main' branch push in the dev repo

jobs:
  push_code_to_prod:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the current dev repository
      - name: Checkout Dev Repository
        uses: actions/checkout@v2

      # Step 2: Set up Git user credentials
      - name: Set up Git user
        run: |
          git config --global user.name "soumya-work"
          git config --global user.email "soumyaranjansahuwork@gmail.com"

      # Step 3: Add Prod repository as a remote
      - name: Add Prod Repository as Remote
        run: |
          git remote add prod https://${{ secrets.API_TOKEN_GITHUB }}@github.com/soumya-work/prodweb.git

      # Step 4: Push to Prod repository main branch
      - name: Push Changes
        run: |
          git push prod main --force
