name: Push Code to Another Repo

on:
  push:
    branches:
      - master # Trigger this on the 'master' branch push

jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code from the current repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Git for pushing code
      - name: Set up Git
        run: |
          git config --global user.name "soumya-work"
          git config --global user.email "soumyaranjansahuwork@gmail.com"

      # Step 3: Add target repository as remote
      - name: Add target repository as remote
        run: git remote add origin https://<PAT>@github.com/soumya-work/devcode.git

      # Step 4: Push to Target Repository
      - name: Push to Target Repository
        run: |
          git push -u origin main --force
        env:
          PAT: ${{ secrets.PAT }} # Use PAT for pushing to the target repo
