# Navigate to your devcode repository
cd path/to/devcode

# Create the directories if they don't exist
mkdir -p .github/workflows

# Create the workflow file
echo "name: Push Code from Devcode to Prodweb

on:
  push:
    branches:
      - main

jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'soumya-work'
          git config --global user.email 'soumyaranjansahuwork@gmail.com'

      - name: Ensure Main Branch Exists
        run: |
          git checkout main || git checkout -b main

      - name: Ensure Commit Exists
        run: |
          if [ -z \"\$(git log -1 --pretty=format:%H)\" ]; then
            echo 'No commits found. Creating initial commit.'
            echo 'Initial file' > README.md
            git add README.md
            git commit -m 'Initial commit'
          else
            echo 'Commits found.'
          fi

      - name: Set target repository as remote
        run: |
          git remote set-url prodweb https://\${{ secrets.PAT }}@github.com/soumya-work/prodweb.git

      - name: Push to Prodweb Repository
        run: |
          git push -u prodweb main --force
" > .github/workflows/workflow.yml

# Add and commit the changes
git add .github/workflows/workflow.yml
git commit -m "Add GitHub Actions workflow to push code to Prodweb"
git push origin main
