name: Push Code from Devcode to Prodweb

on:
  push:
    branches:
      - main # Trigger this on the 'main' branch push

jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code from the current repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Git for pushing code
      - name: Set up Git
        run: |
          git config --global user.name "soumya-work"
          git config --global user.email "soumyaranjansahuwork@gmail.com"

      # Step 3: Ensure Main Branch Exists
      - name: Ensure Main Branch Exists
        run: |
          git checkout main || git checkout -b main

      # Step 4: Ensure Commit Exists
      - name: Ensure Commit Exists
        run: |
          if [ -z "$(git log -1 --pretty=format:%H)" ]; then
            echo "No commits found. Creating initial commit."
            echo "Initial file" > README.md
            git add README.md
            git commit -m "Initial commit"
          else
            echo "Commits found."
          fi

      # Step 5: Set target repository as remote
      - name: Set target repository as remote
        run: |
          git remote set-url prodweb https://${{ secrets.PAT }}@github.com/soumya-work/prodweb.git

      # Step 6: Push to Prodweb Repository
      - name: Push to Prodweb Repository
        run: |
          git push -u prodweb main --force
