name: Push Code from Devcode Main to Prodweb Beta

on:
  push:
    branches:
      - main # Trigger this on the 'main' branch push

jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code from the current repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Git for pushing code
      - name: Set up Git
        run: |
          git config --global user.name "soumya-work"
          git config --global user.email "soumyaranjansahuwork@gmail.com"

      # Step 3: Ensure Main Branch Exists in Dev Repo
      - name: Ensure Main Branch Exists
        run: |
          git checkout main || git checkout -b main

      # Step 4: Ensure Commit Exists in Main Branch
      - name: Ensure Commit Exists
        run: |
          if [ -z "$(git log -1 --pretty=format:%H)" ]; then
            echo "No commits found. Creating initial commit."
            echo "Initial file" > README.md
            git add README.md
            git commit -m "Initial commit"
          else
            echo "Commits found."
          fi

      # Step 5: Add target repository (prodweb) as remote
      - name: Add target repository as remote
        run: |
          git remote add prodweb https://github-actions:${{ secrets.PAT }}@github.com/soumya-work/prodweb.git

      # Step 6: Check if 'beta' branch exists in Prodweb
      - name: Check for 'beta' branch in Prodweb
        id: check_branch
        run: |
          if git ls-remote --exit-code --heads prodweb beta; then
            echo "Branch exists" && echo "exists=true" >> $GITHUB_ENV
          else
            echo "Branch does not exist" && echo "exists=false" >> $GITHUB_ENV
          fi

      # Step 7: Create 'beta' branch if Not Existing
      - name: Create Beta Branch if Not Existing
        if: env.exists == 'false'
        run: |
          git checkout -b beta
          git push prodweb beta

      # Step 8: Push changes from 'main' branch of Dev to 'beta' branch of Prod
      - name: Push to Prodweb Beta Branch
        run: |
          git push prodweb main:beta --force
